apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: proj7
  region: us-east-1
  version: "1.21"

vpc:
  id: vpc-0e35f52e44ade4a32
  subnets:
    private:
      us-east-1a: 
        id: subnet-090a10c8782f7065c
      us-east-1b: 
        id: subnet-0c23173f9d174a6c4
    public:
      us-east-1c: 
        id: subnet-08467420d7306c0e0
      us-east-1d: 
        id: subnet-05a33fa8e9ea5cbd5
#availabilityZones:
#- us-east-1a
#- us-east-1b
#- us-east-1c
managedNodeGroups:
  - name: cilist
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 4

    #volumeSize: 10
    privateNetworking: true

#availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']
#    privateNetworking: true