apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cilsy
  region: us-east-1
  version: "1.21"

#vpc:
#  id: vpc-07c6923006dddfd5a
#  subnets:
#    private:
#      us-east-1a: {id: subnet-034e6de05a2c61e61}
#      us-east-1b: {id: subnet-041993b594be17c95}
#    public:
#      us-east-1c: {id: subnet-021a9d64e8cfb11b2}

managedNodeGroups:
  - name: ngcilsy
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 

availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']
#    privateNetworking: true