apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::064887354011:user/eksctl
      username: eksctl
      groups:
        - system:masters
