apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::09:jkpraja/github-ci
      username: arn:aws:iam::09:jkpraja/github-ci
      groups:
        - system:masters
