apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj7-be
  #namespace: devops-jkpraja
spec:
  selector:
    matchLabels:
      app: proj7-be
  template:
    metadata:
      labels:
        app: proj7-be
    spec:
      containers:
      - name: proj7-be
        image: jkpraja/be:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: be-configmap
              key: db_host
        #- name: BASE_URL_PORT
        #  valueFrom:
        #    configMapKeyRef:
        #      name: be-configmap
        #      key: base_url_port
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: db-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: db-password
        - name: DATABASE_DATABASE
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: db-name
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"
