apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj7-db
  #namespace: devops-jkpraja
spec:
  selector:
    matchLabels:
      app: proj7-db
  template:
    metadata:
      labels:
        app: proj7-db
    spec:
      volumes:
        - name: import-db
          configMap:
            name: db-configmap
      containers:
      - name: proj7-db
        image: jkpraja/db:latest
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: import-db
          mountPath: "/docker-entrypoint-initdb.d/crud_db.sql"
          subPath: "crud_db.sql"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-master-pwd
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-pwd
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-configmap
                key: db-name
