name: cd
#run-name: ${{ github.actor }} is learning GitHub Actions
on:
  #pull_request:
  #  branches:
  #    - master
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.3'
        id: Install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
      - name: Use context
        run: aws eks update-kubeconfig --name proj7 --region us-east-1
      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f 'configs/2 - frontend'
          kubectl apply -f 'configs/3 - backend'