name: ci

#on:
#  push:
#    branches: master

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push frontend to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: jkpraja/frontend:latest, jkpraja/frontend:${{ github.run_number }}
      - name: Build and push backend to docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: jkpraja/backend:latest, jkpraja/frontend:${{ github.run_number }}