
name: ci
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    branches:
      - master
  #push:
  #  branches:
  #    - master

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push frontend to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: jkpraja/frontend:latest, jkpraja/frontend:${{ github.run_number }}
      - name: Build and push backend to docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: jkpraja/backend:latest, jkpraja/backend:${{ github.run_number }}
  deploy-image-to-eks:
    runs-on: ubuntu-latest
    needs: build-container
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.3'
        id: Install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name proj7 --region us-east-1
      
      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f eks/aws-auth.yaml
          kubectl apply -f 'configs/2 - frontend'
          kubectl apply -f 'configs/3 - backend'